/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BytesLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  DAOVerifier,
  DAOVerifierInterface,
} from "../../contracts/DAOVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_merkleRoot",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "merkleRoot",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "proof",
        type: "bytes32[]",
      },
      {
        internalType: "uint64",
        name: "maxAllowanceToMint",
        type: "uint64",
      },
    ],
    name: "verifyIsIncluded",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60803461005157601f61025138819003918201601f19168301916001600160401b038311848410176100565780849260209460405283398101031261005157516000556040516101e4908161006d8239f35b600080fd5b634e487b7160e01b600052604160045260246000fdfe6080604081815260048036101561001557600080fd5b600092833560e01c9182630d9456b414610059575050632eb4a7ab1461003a57600080fd5b34610055578160031936011261005557602091549051908152f35b5080fd5b849192503461005557836003193601126100555780359367ffffffffffffffff938486116101aa57366023870112156101aa57858301358581116101a65760059681881b92602498898584010198368a116101a2578a3599818b16809b0361019e576020958685019b338d5289860152888552606085019b8c8487821091111761018c578c8a52855190209260608c5499603f601f19910116870101908d82109082111761018c5789528b526080948c01868587015b83831061017c57505050509488955b8a518710156101725786831b84018501519081811015610165578a5285528689205b956000198114610153576001019561011e565b634e487b7160e01b8a52601189528b8afd5b908a528552868920610140565b8591885191148152f35b823581529181019188910161010f565b634e487b7160e01b8c5260418b528d8cfd5b8980fd5b8880fd5b8480fd5b8380fdfea2646970667358221220635cd93398c3d666c1522093ebda1f83e08f78dba82ff05ce9debb7400b4550464736f6c63430008120033";

type DAOVerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DAOVerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DAOVerifier__factory extends ContractFactory {
  constructor(...args: DAOVerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _merkleRoot: BytesLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_merkleRoot, overrides || {});
  }
  override deploy(
    _merkleRoot: BytesLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_merkleRoot, overrides || {}) as Promise<
      DAOVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): DAOVerifier__factory {
    return super.connect(runner) as DAOVerifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DAOVerifierInterface {
    return new Interface(_abi) as DAOVerifierInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): DAOVerifier {
    return new Contract(address, _abi, runner) as unknown as DAOVerifier;
  }
}
