/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Development } from "./ERC20Development";
export type { ERC721Development } from "./ERC721Development";
