export enum BlockchainProposalStatus {
    CREATED_OFFCHAIN = 'CREATED_OFFCHAIN',
    READY_TO_DEPLOY_ONCHAIN = 'READY_TO_DEPLOY_ONCHAIN',
    PROPOSAL_REJECTED = 'PROPOSAL_REJECTED',
    CREATED_ON_CHAIN = 'CREATED_ON_CHAIN',
    READY_TO_EXECUTE = 'READY_TO_EXECUTE',
    REJECTED_ONCHAIN = 'REJECTED_ONCHAIN',
    EXECUTED = 'EXECUTED',
}
